ingredients/urls.py
from django.urls import path
from .views import IngredientListView, IngredientDetailView, IngredientCreateView

app_name = 'ingredients'

urlpatterns = [
    path('list/', IngredientListView.as_view(), name='ingredient_list'),
    path('list/<pk>', IngredientDetailView.as_view(), name='ingredient-detail'),
    path('add/', IngredientCreateView.as_view(), name='add_ingredient'),
]

recipe_project/urls.py
from django.contrib import admin

from django.urls import path
from django.urls import include
from django.views.generic import TemplateView
# home page
from recipes.views import home
# for the urls of static pics
from django.conf import settings
from django.conf.urls.static import static

from .views import login_view, logout_success

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('recipes/', include('recipes.urls')),
    path('ingredients/', include('ingredients.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_success, name='logout_success'),
    path("about/", TemplateView.as_view(template_name="about.html"), name="about"),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import home
from .views import RecipeListView, RecipeDetailView, ingredient_search
from .views import RecipeCreateView, RecipeIngredientCreateView

app_name = 'recipes'

urlpatterns = [
    path('', home),
    path('list/', RecipeListView.as_view(), name='recipe_list'),
    path('list/<pk>', RecipeDetailView.as_view(), name='recipe_detail'),
    path("ingredient-search/", ingredient_search, name="ingredient_search"),
    path('new/', RecipeCreateView.as_view(), name='recipe_create'),
    path('recipe/<int:recipe_id>/add_ingredients/', RecipeIngredientCreateView.as_view(), name='recipe_add_ingredients'),
]

ingredients/models.py
from django.db import models
from django.shortcuts import reverse


class Ingredient(models.Model):
    name = models.CharField(max_length=120, unique=True,
                            db_index=True)
    introduction = models.TextField(blank=True, null=True)
    pic = models.ImageField(upload_to='ingredients', default='no_picture.jpg')

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
       return reverse ('ingredients:ingredient-detail', kwargs={'pk': self.pk})

ingredients/forms.py
from django import forms
from .models import Ingredient

class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ['name', 'introduction', 'pic']

ingredients/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView   #to display lists and details
from django.shortcuts import redirect
from .models import Ingredient               #to access Ingredient model

from .forms import IngredientForm
from django.urls import reverse_lazy

from recipesingredients.models import RecipeIngredient

# Create your views here.
class IngredientListView(ListView):           #class-based view
   model = Ingredient                         #specify model
   template_name = 'ingredients/list.html'    #specify template 

class IngredientDetailView(DetailView):  # class-based view
    model = Ingredient  # specify model
    template_name = 'ingredients/detail.html'  # specify template

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["recipes"] = RecipeIngredient.objects.filter(
            ingredient=self.object)
        return context
    

class IngredientCreateView(CreateView):
    model = Ingredient
    form_class = IngredientForm
    template_name = "ingredients/ingredient_form.html"

    def form_valid(self, form):
        """store new ingredient and go back to Recipe add ingredient page"""
        self.object = form.save()
        return redirect(reverse_lazy('recipes:recipe_add_ingredients', kwargs={'recipe_id': self.request.GET.get('recipe_id', 1)}))

ingredients/templates/ingredients/detail.html
{% extends 'base.html' %}  <!-- 繼承 base.html -->

{% block content %}
    <h2>Details: {{ object.name }}</h2>
    <img src="{{ object.pic.url }}" height="300" /><br>

    <b>Title: </b> {{ object.name }}  <br>

    <b>Introduction: </b> {{ object.introduction }} <br>

    <h3>Related Recipes:</h3>
    <ul>
      {% for recipe in recipes %}
        <li>
          <a href="{% url 'recipes:recipe_detail' recipe.recipe.id %}">
            {{ recipe.recipe.name }}
          </a>
        </li>
      {% empty %}
        <li>No recipe listed.</li>
      {% endfor %}
    </ul>
{% endblock %}

ingredients/templates/ingredients/ingredient_form.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1 class="text-center my-4">Add New Ingredient</h1>
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="mb-3">
            {{ form.name.label_tag }}
            {{ form.name }}
        </div>

        <div class="mb-3">
            {{ form.introduction.label_tag }}
            {{ form.introduction }}
        </div>

        <div class="mb-3">
            {{ form.pic.label_tag }}
            {{ form.pic }}
        </div>

        <button type="submit" class="btn btn-primary">Save Ingredient</button>
        <a href="{% url 'recipes:recipe_add_ingredients' recipe_id=request.GET.recipe_id %}" class="btn btn-secondary">Back to Recipe</a>
    </form>
</div>
{% endblock %}

ingredients/templates/ingredients/list.html
{% extends "base.html" %}

{% block title %}Ingredients List{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1 class="text-center mb-4">Ingredients' List</h1>

    <div class="row">
        {% for object in object_list %}
        <div class="col-md-4 mb-4">
            <div class="card recipe-card">
                <a href="{{ object.get_absolute_url }}">
                    <img
                        src="{{ object.pic.url }}"
                        class="card-img-top"
                        alt="{{ object.name }}"
                    />
                </a>
                <div class="card-body">
                    <a href="{{ object.get_absolute_url }}">
                        <h5 class="recipe-title">{{ object.name }}</h5>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}